# Generated by Django 4.2.7 on 2025-11-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20251125_2300'),
        ('payments', '0002_auto_20251125_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttransaction',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='shipping.shipment'),
        ),
    ]
