# Generated by Django 4.2.7 on 2025-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_shipmenttransaction_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
