# Generated by Django 4.2.7 on 2025-11-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]
