# Generated by Django 4.2.7 on 2025-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251125_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
