# Generated by Django 4.2.7 on 2025-11-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_alter_merchantcore_integrations_and_more'),
        ('core', '0003_company_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='merchant_core',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='platform_core.merchantcore'),
        ),
    ]
