# Generated by Django 4.2.7 on 2025-11-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.company'),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.company'),
        ),
        migrations.AddField(
            model_name='carrierperformance',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='carrierperformance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_performance', to='core.company'),
        ),
        migrations.AddField(
            model_name='apiusagestats',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='core.apikey'),
        ),
        migrations.AddField(
            model_name='apiusagestats',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_stats', to='core.company'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['date'], name='performance_date_7d1a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['company', 'date'], name='performance_company_301cad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('company', 'date')},
        ),
        migrations.AddIndex(
            model_name='carrierperformance',
            index=models.Index(fields=['carrier', 'date'], name='carrier_per_carrier_a4a668_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierperformance',
            index=models.Index(fields=['company', 'date'], name='carrier_per_company_9e2bbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrierperformance',
            unique_together={('carrier', 'company', 'date')},
        ),
        migrations.AddIndex(
            model_name='apiusagestats',
            index=models.Index(fields=['company', 'date'], name='api_usage_s_company_b4f273_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagestats',
            index=models.Index(fields=['api_key', 'date'], name='api_usage_s_api_key_e7b2ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiusagestats',
            unique_together={('company', 'api_key', 'date', 'hour')},
        ),
    ]
