# Generated by Django 4.2.7 on 2025-11-25 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('shipping', 'Shipping'), ('payment', 'Payment'), ('analytics', 'Analytics'), ('notification', 'Notification'), ('storage', 'Storage'), ('integration', 'Integration')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('max_requests_per_minute', models.IntegerField(default=1000)),
                ('max_requests_per_hour', models.IntegerField(default=10000)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Service',
                'verbose_name_plural': 'Core Services',
                'db_table': 'core_services',
            },
        ),
        migrations.CreateModel(
            name='PlatformCore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Send-Pakket', max_length=255)),
                ('platform_version', models.CharField(default='1.0.0', max_length=50)),
                ('platform_domain', models.CharField(default='sendpakket.com', max_length=255)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('password_min_length', models.IntegerField(default=8)),
                ('max_concurrent_requests', models.IntegerField(default=1000)),
                ('rate_limit_per_minute', models.IntegerField(default=100)),
                ('cache_timeout_seconds', models.IntegerField(default=3600)),
                ('supported_currencies', models.JSONField(default=list, help_text='العملات المدعومة')),
                ('supported_languages', models.JSONField(default=list, help_text='اللغات المدعومة')),
                ('supported_countries', models.JSONField(default=list, help_text='الدول المدعومة')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('backup_frequency_hours', models.IntegerField(default=24)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('total_merchants', models.IntegerField(default=0)),
                ('total_shipments', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('system_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance'), ('down', 'Down')], default='operational', max_length=20)),
                ('features_enabled', models.JSONField(default=dict, help_text='الميزات المفعلة')),
                ('custom_settings', models.JSONField(default=dict, help_text='إعدادات مخصصة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Core',
                'verbose_name_plural': 'Platform Core',
                'db_table': 'platform_core',
            },
        ),
        migrations.CreateModel(
            name='MerchantCore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(help_text='معرف التاجر الفريد', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('dropshipping', 'Dropshipping'), ('marketplace', 'Marketplace')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('settings', models.JSONField(default=dict, help_text='إعدادات التاجر المخصصة')),
                ('preferences', models.JSONField(default=dict, help_text='تفضيلات التاجر')),
                ('monthly_shipment_limit', models.IntegerField(default=1000)),
                ('api_rate_limit', models.IntegerField(default=100)),
                ('storage_limit_mb', models.IntegerField(default=1000)),
                ('total_shipments', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_shipments', models.IntegerField(default=0)),
                ('integrations', models.JSONField(default=dict, help_text='التكاملات المفعلة')),
                ('security_settings', models.JSONField(default=dict, help_text='إعدادات الأمان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('platform_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_core.platformcore')),
            ],
            options={
                'verbose_name': 'Merchant Core',
                'verbose_name_plural': 'Merchant Cores',
                'db_table': 'merchant_cores',
            },
        ),
        migrations.CreateModel(
            name='CoreMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('performance', 'Performance'), ('usage', 'Usage'), ('error', 'Error'), ('business', 'Business')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(default='count', max_length=20)),
                ('tags', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('core_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.coreservice')),
                ('merchant_core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.merchantcore')),
            ],
            options={
                'verbose_name': 'Core Metric',
                'verbose_name_plural': 'Core Metrics',
                'db_table': 'core_metrics',
            },
        ),
        migrations.CreateModel(
            name='CoreEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('system', 'System Event'), ('merchant', 'Merchant Event'), ('service', 'Service Event'), ('security', 'Security Event'), ('performance', 'Performance Event')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('core_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.coreservice')),
                ('merchant_core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.merchantcore')),
            ],
            options={
                'verbose_name': 'Core Event',
                'verbose_name_plural': 'Core Events',
                'db_table': 'core_events',
            },
        ),
        migrations.CreateModel(
            name='CoreConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('merchant', 'Merchant'), ('service', 'Service'), ('regional', 'Regional')], default='global', max_length=20)),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_core.coreservice')),
                ('merchant_core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_core.merchantcore')),
            ],
            options={
                'verbose_name': 'Core Configuration',
                'verbose_name_plural': 'Core Configurations',
                'db_table': 'core_configurations',
            },
        ),
        migrations.CreateModel(
            name='MerchantService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('merchant_config', models.JSONField(default=dict, help_text='إعدادات التاجر لهذه الخدمة')),
                ('custom_limits', models.JSONField(default=dict, help_text='حدود مخصصة للتاجر')),
                ('usage_count', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_core.coreservice')),
                ('merchant_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_core.merchantcore')),
            ],
            options={
                'verbose_name': 'Merchant Service',
                'verbose_name_plural': 'Merchant Services',
                'db_table': 'merchant_services',
                'unique_together': {('merchant_core', 'core_service')},
            },
        ),
        migrations.AddIndex(
            model_name='merchantcore',
            index=models.Index(fields=['merchant_id'], name='merchant_co_merchan_8ba11f_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcore',
            index=models.Index(fields=['status'], name='merchant_co_status_5c3851_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcore',
            index=models.Index(fields=['business_type'], name='merchant_co_busines_7cfdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='coremetric',
            index=models.Index(fields=['metric_type', 'recorded_at'], name='core_metric_metric__d3e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='coremetric',
            index=models.Index(fields=['metric_name', 'recorded_at'], name='core_metric_metric__50e6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='coremetric',
            index=models.Index(fields=['merchant_core', 'recorded_at'], name='core_metric_merchan_5ffe40_idx'),
        ),
        migrations.AddIndex(
            model_name='coreevent',
            index=models.Index(fields=['event_type', 'created_at'], name='core_events_event_t_ab6111_idx'),
        ),
        migrations.AddIndex(
            model_name='coreevent',
            index=models.Index(fields=['level', 'created_at'], name='core_events_level_ef19d4_idx'),
        ),
        migrations.AddIndex(
            model_name='coreevent',
            index=models.Index(fields=['merchant_core', 'created_at'], name='core_events_merchan_53ea4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coreconfiguration',
            unique_together={('scope', 'config_key', 'merchant_core', 'core_service')},
        ),
    ]
