# Generated by Django 4.2.7 on 2025-11-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
