# Generated by Django 4.2.7 on 2025-11-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_fix_core_event_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantcore',
            name='integrations',
            field=models.JSONField(default=dict, help_text='Enabled integrations'),
        ),
        migrations.AlterField(
            model_name='merchantcore',
            name='merchant_id',
            field=models.CharField(help_text='Unique merchant identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantcore',
            name='preferences',
            field=models.JSONField(default=dict, help_text='Merchant preferences'),
        ),
        migrations.AlterField(
            model_name='merchantcore',
            name='security_settings',
            field=models.JSONField(default=dict, help_text='Security settings'),
        ),
        migrations.AlterField(
            model_name='merchantcore',
            name='settings',
            field=models.JSONField(default=dict, help_text='Merchant custom settings'),
        ),
        migrations.AlterField(
            model_name='merchantservice',
            name='custom_limits',
            field=models.JSONField(default=dict, help_text='Custom limits for merchant'),
        ),
        migrations.AlterField(
            model_name='merchantservice',
            name='merchant_config',
            field=models.JSONField(default=dict, help_text='Merchant settings for this service'),
        ),
        migrations.AlterField(
            model_name='platformcore',
            name='custom_settings',
            field=models.JSONField(default=dict, help_text='Custom settings'),
        ),
        migrations.AlterField(
            model_name='platformcore',
            name='features_enabled',
            field=models.JSONField(default=dict, help_text='Enabled features'),
        ),
        migrations.AlterField(
            model_name='platformcore',
            name='supported_countries',
            field=models.JSONField(default=list, help_text='Supported countries'),
        ),
        migrations.AlterField(
            model_name='platformcore',
            name='supported_currencies',
            field=models.JSONField(default=list, help_text='Supported currencies'),
        ),
        migrations.AlterField(
            model_name='platformcore',
            name='supported_languages',
            field=models.JSONField(default=list, help_text='Supported languages'),
        ),
    ]
