# Generated by Django 4.2.7 on 2025-11-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('carriers', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierwebhook',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_webhooks', to='core.company'),
        ),
        migrations.AddField(
            model_name='carrierservice',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='carrierpricing',
            name='carrier_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='carriers.carrierservice'),
        ),
        migrations.AddField(
            model_name='carriercredentials',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='carriercredentials',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_credentials', to='core.company'),
        ),
        migrations.AddField(
            model_name='carrierapilog',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='carrierapilog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='carrierapilog',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shipment'),
        ),
        migrations.AlterUniqueTogether(
            name='carrierservice',
            unique_together={('carrier', 'code')},
        ),
        migrations.AddIndex(
            model_name='carrierpricing',
            index=models.Index(fields=['carrier_service', 'origin_country', 'destination_country'], name='carrier_pri_carrier_5c26b8_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierpricing',
            index=models.Index(fields=['effective_from', 'effective_to'], name='carrier_pri_effecti_665915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carriercredentials',
            unique_together={('company', 'carrier')},
        ),
        migrations.AddIndex(
            model_name='carrierapilog',
            index=models.Index(fields=['carrier', 'created_at'], name='carrier_api_carrier_b8af65_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierapilog',
            index=models.Index(fields=['company', 'created_at'], name='carrier_api_company_16eb82_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierapilog',
            index=models.Index(fields=['status_code', 'created_at'], name='carrier_api_status__73248a_idx'),
        ),
    ]
